### ISSUE TITLE
rally.yml "projects" property cannot be omitted (commented out) w/out causing a failure

### ISSUE THREAD

**Issue by fslama** [github/rally#106]
**Describe the bug**

rally.yml file contains:
```
      # Which projects this repo will link to.
      # To have it connect to any project, leave this value blank
      projects:
      #  - Sample Project

```
If "projects:" is commented out the application will fail with an error (See below) and not process the check.

**To Reproduce**
1. Follow standard installation steps for project 
2. When configuring rally.yml comment out the projects: property (and associated values below it),
3. Start application (I.e. npm start) and monitor output
4. Issue a commit under repository that application is monitoring
5. Watch for error and check failure.

**Expected behavior**
If "projects:" yml configuration is commented out the application should not fail, but still communicate with Rally (ignoring specific project).

```
9:12:20.665Z ERROR event: Cannot read property 'map' of undefined (id=bbbfd500-e186-11ea-99fc-f0362d48b04c)
  TypeError: Cannot read property 'map' of undefined
      at RallyValidate.processArtifacts (/opt/gitrallyapp/lib/RallyValidate.js:255:56)
      at RallyValidate.handlePullRequest (/opt/gitrallyapp/lib/RallyValidate.js:171:53)
  --
  event: {
    "event": "pull_request.edited",
    "id": "bbbfd500-e186-11ea-99fc-f0362d48b04c",
    "installation": 291,
    "repository": "ESD/DA"
  }
19:12:20.665Z ERROR probot: Cannot read property 'map' of undefined
  TypeError: Cannot read property 'map' of undefined
      at RallyValidate.processArtifacts (/opt/gitrallyapp/lib/RallyValidate.js:255:56)
      at RallyValidate.handlePullRequest (/opt/gitrallyapp/lib/RallyValidate.js:171:53)
19:12:20.665Z  INFO http: POST / 500 - 1373.21 ms (id=bbbfd500-e186-11ea-99fc-f0362d48b04c)
19:12:20.665Z TRACE http:  (id=bbbfd500-e186-11ea-99fc-f0362d48b04c, res.duration=1373.21)
  HTTP/1.1 500 Internal Server Error
  x-powered-by: Express
  x-request-id: bbbfd500-e186-11ea-99fc-f0362d48b04c
```

**Comment by primetheus** [comment]
@fslama thanks for opening this up! I've got a fix for this in #108
